Document: rippled
Title: Debian rippled Manual
Author: <insert document author here>
Abstract: This manual describes what rippled is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rippled/rippled.sgml.gz

Format: postscript
Files: /usr/share/doc/rippled/rippled.ps.gz

Format: text
Files: /usr/share/doc/rippled/rippled.text.gz

Format: HTML
Index: /usr/share/doc/rippled/html/index.html
Files: /usr/share/doc/rippled/html/*.html
